version: '3.8'

services:
  web:
    image: palleoptimering
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=Palleoptimering;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: "1433"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

volumes:
  db_data:
