version: '3.4'

services:
  web:
    image: palleoptimering:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 10s
      retries: 5
