// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palleoptimering.Models;

#nullable disable

namespace Palleoptimering.Migrations.PalletSettingsDb
{
    [DbContext(typeof(PalletSettingsDbContext))]
    [Migration("20241211133800_PalletSettingsInitialCreate")]
    partial class PalletSettingsInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Palleoptimering.Models.PalletSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowTurningOverMaxHeight")
                        .HasColumnType("bit");

                    b.Property<int>("AllowedStackingMaxWeight")
                        .HasColumnType("int");

                    b.Property<int>("EndPlate")
                        .HasColumnType("int");

                    b.Property<double>("HeightWidthFactor")
                        .HasColumnType("float");

                    b.Property<bool>("HeightWidthFactorOnlyForOneElement")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLayers")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpace")
                        .HasColumnType("int");

                    b.Property<double>("StackingMaxHeight")
                        .HasColumnType("float");

                    b.Property<int>("WeightAllowedToTurnElement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PalletSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
